- name: CI/CD Deployment mit Ansible und ArgoCD
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pull latest code from Git
      ansible.builtin.git:
        repo: "https://github.com/kevinjaegle/my-argocd-app.git"
        dest: "/tmp/my-argocd-app"
        update: yes

    - name: Update Image-Version in Helm values.yaml
      ansible.builtin.replace:
        path: "/mnt/c/Users/kevin/Desktop/Projects/my-cluster/my-argocd-app/my-helm-app/values.yaml"
        regexp: 'tag: .*'
        replace: 'tag: "{{ new_version }}"'

    - name: Commit & Push neue Version
      args:
        chdir: "/tmp/my-argocd-app"
      shell: |
        git add my-helm-app/values.yaml
        git commit -m "Update auf neue Version {{ new_version }}"
        git push origin main

    - name: ArgoCD App Sync auslösen
      command: argocd app sync my-helm-app
